# Generated by Django 4.0.4 on 2022-05-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="Имя"),
        ),
    ]
