# Generated by Django 4.0.4 on 2022-05-28 05:36

from django.db import migrations, models
import django.db.models.deletion
import wallet.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(verbose_name='Владелец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Связь кошелек-пользователь',
                'verbose_name_plural': 'Связи кошелек-пользователь',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Всего')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала срока')),
                ('date_update', models.DateField(blank=True, null=True, verbose_name='Дата последнего обновления лимитов')),
                ('days_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество дней срока')),
                ('sample_daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Эталонный лимит на день')),
                ('current_daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Текущий лимит на день')),
                ('users', models.ManyToManyField(through='wallet.UserWallet', to='users.user', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.AddField(
            model_name='userwallet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet', verbose_name='Кошелек'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=wallet.utils.get_short_uuid, max_length=8)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet', verbose_name='Кошелек')),
            ],
            options={
                'verbose_name': 'Инвайт',
                'verbose_name_plural': 'Инвайты',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userwallet',
            unique_together={('user', 'wallet')},
        ),
    ]
