# Generated by Django 4.0.4 on 2022-05-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.BooleanField(verbose_name="Владелец")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кошелек и пользователь",
                "verbose_name_plural": "Кошельки и пользователи",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        through="wallet.UserWallet", to="users.user", verbose_name="Пользователи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кошелек",
                "verbose_name_plural": "Кошельки",
            },
        ),
        migrations.AddField(
            model_name="userwallet",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.wallet",
                verbose_name="Кошелек",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Значение"),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.wallet",
                        verbose_name="Кошелек",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
            },
        ),
        migrations.AlterUniqueTogether(
            name="userwallet",
            unique_together={("user", "wallet")},
        ),
    ]
